name: Android CI

on:
    schedule:
    - cron:  '0 8 * * 1-5'
    #schedule:
          #     Run every 5 mins
          #- cron:  '*/5 * * * *'
          
           #    This example triggers the workflow every day at 5:30 and 17:30 UTC:
           #    * is a special character in YAML so you have to quote this string
           #    - cron:  '30 5,17 * * *'
           
    #push:
    #    branches: [ master ]
    #pull_request:
    #    branches: [ master ]
           
#    workflow_dispatch: 
    workflow_dispatch: # to be able to run action manually 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build
        
  test: 
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 1
