name: Java CI

on:
    schedule: 
          - cron:  '*/5 * * * *'
          
           #    This example triggers the workflow every day at 5:30 and 17:30 UTC:
           #    * is a special character in YAML so you have to quote this string
           #    - cron:  '30 5,17 * * *'
           
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
           
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build
