name: Slack API testing

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  slack:
    runs-on: ubuntu-latest

    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
          args: '{\"channel\":\"C02E6Q6HAKV\",\"attachments\":[{\"pretext\":\"My text\",\"text\": \"github itself: ${{ toJson(github) }} \n env: ${{ env }} \n job: ${{ job }} \n steps: ${{ steps }} \" }]}'
#        args: '{\"channel\":\"C02E6Q6HAKV\",\"attachments\":[{\"text\":\"My text\",\"pretext\": \"github event: ${{ toJson(github.event) }} \n github itself: ${{ toJson(github) }} \n\" }]}'
