name: Slack API testing

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  slack:
    runs-on: ubuntu-latest

    steps:
    - name: Notify slack github full
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
          args: '{\"channel\":\"C02E6Q6HAKV\",\"attachments\":[{\"pretext\":\"Github info\",\"text\": \"github itself: ${{ toJson(github) }} \" }]}'

    - name: Notify slack env full
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
          args: '{\"channel\":\"C02E6Q6HAKV\",\"attachments\":[{\"pretext\":\"Env info\",\"text\": \"env: ${{ toJson(env) }} \" }]}'
          
    - name: Notify slack job full
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
          args: '{\"channel\":\"C02E6Q6HAKV\",\"attachments\":[{\"pretext\":\"Job\",\"text\": \"job: ${{ toJson(job) }} \" }]}'
          
    - name: Notify slack steps full
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
          args: '{\"channel\":\"C02E6Q6HAKV\",\"attachments\":[{\"pretext\":\"Steps\",\"text\": \"steps: ${{ toJson(steps) }} \" }]}'
          
    - name: Notify slack commits
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
          args: '{\"channel\":\"C02E6Q6HAKV\",\"attachments\":[{\"pretext\":\"Steps\",\"text\": \"steps: ${{ toJson(github.event.head_commit) }} \" }]}'
          
#        args: '{\"channel\":\"C02E6Q6HAKV\",\"attachments\":[{\"text\":\"My text\",\"pretext\": \"github event: ${{ toJson(github.event) }} \n github itself: ${{ toJson(github) }} \n\" }]}'
